### ISSUE TITLE
Initialization issues due to directional derivatives.

### ISSUE THREAD

**Issue by chria** [NREL/SOEP-QSS-Test#8]
PyFMI and QSS runs fail for some models built with directional derivative support, aborting with no error message during FMU initialization:

DataCenterContinuousTimeControl
DataCenterDiscreteTimeControl
SimpleHouse
SimpleHouseDiscreteTime

**Comment by DeadParrot** [comment]
### Versions

The issue was observed with these component versions (may occur with others):

Component | Version                            | Date
------------- | --------------------------- | ----------
OCT             | OCT-r23206_JM-r14295  | 2021/05
Buildings     | 9c37781                           | 2021/05/04
QSS             | e4a0f62                            | 2021/06/08

### Build

Build the FMU with `bld` from the OCT directory as described in the [Status](https://github.com/NREL/SOEP-QSS-Test/blob/main/Status.md) page.

### Run

Run the models with PyFMI or QSS from a console configured as described in the [Status](https://github.com/NREL/SOEP-QSS-Test/blob/main/Status.md) page.

**PyFMI**: Use `run` under the model `OCT` directories to generate the CVode simulation.

**QSS**: Use `run` under the model `QSS` directory in a method subdirectory such as `QSS2`.

**Comment by DeadParrot** [comment]
With a more recent OCT version the PyFMI simulation of the DataCenterContinuousTimeControl, DataCenterDiscreteTimeControl, and SimpleHouse FMUs built with directional derivative support run to completion.

Component | Version                            | Date
------------- | --------------------------- | ----------
OCT             | OCT-r26747_JM-r14295  | 2021/12/15
Buildings     | 73ff5b8                            | 2021/12/23

The early part of the two DataCenter simulations differ from the prior results without directional derivatives enabled, having somewhat "noisier" trajectories before settling down.

SimpleHouseDiscreteTime will not run with this newer Buildings library.

I am leaving this issue open pending testing on the other models and with the revamped QSS under development.

**Comment by DeadParrot** [comment]
With the OCT dev build OCT-dev-cw-5212-18478f3488ff1272c52222a29d72215983eadeec the same three models (updated from the latest Buildings Library) still build and run cleanly with directional derivative support.

Given the current lack of models known to have problems with directional derivative support enabled I am closing this Issue.

Any problems with the simulation trajectories/stability of the DataCenter models will be addressed in a separate Issue if needed.
